from selenium import webdriver
import json
import requests
import datetime
import csv

#can add up to 100 tweets to delete at a time 
# calls twitter 
driver_path = './chromedriver'
url = 'https://twitter.com/login'
url1='insert tweet url here '
url2='insert tweet url here'
url3='insert tweet url here'
url4='insert tweet url here'
url5='insert tweet url here'
driver = webdriver.Chrome (driver_path)
driver.get(url)


print 'starting program'

element1 = driver.find_element_by_xpath("//*[@id='page-container']/div/div[1]/form/fieldset/div[1]/input").send_keys('email adress for twitter account')
element2 = driver.find_element_by_xpath("//*[@id='page-container']/div/div[1]/form/fieldset/div[2]/input").send_keys('twitter password')
element3 = driver.find_element_by_xpath(".//button[@type='submit' and @class='submit EdgeButton EdgeButton--primary EdgeButtom--medium']")
driver.execute_script("arguments[0].click();", element3)


element4 = driver.get(url1)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url2)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url3)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url4)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url5)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url6)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url7)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url8)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url9)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url10)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url11)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url12)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url13)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url14)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url15)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url16)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url17)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url18)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url19)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url20)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url21)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url22)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url23)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url24)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url25)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url26)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url27)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url28)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url29)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url30)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url31)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url32)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url33)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url34)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url35)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url36)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url37)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url38)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url39)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url40)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url41)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url42)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url43)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url44)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url45)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url46)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url47)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url48)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url49)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url50)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url51)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url52)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url53)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url54)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url55)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url56)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url57)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url58)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url59)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url60)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url61)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url62)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url63)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url64)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url65)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url66)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url67)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url68)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url69)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url70)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url71)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url72)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url73)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url74)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url75)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url76)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url77)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url78)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url79)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url80)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url81)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url82)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url83)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url84)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url85)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url86)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url87)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url88)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url89)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url90)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url91)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url92)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url93)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url94)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url95)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url96)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url97)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url98)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url99)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)
element10 = driver.get(url100)
element5 = driver.find_element_by_xpath(".//button[@type='button' and @class='ProfileTweet-actionButton u-textUserColorHover dropdown-toggle js-dropdown-toggle']")
driver.execute_script("arguments[0].click();", element5)
element6 = driver.find_element_by_xpath("//*[@id='permalink-overlay-dialog']/div[3]/div/div/div[1]/div[1]/div/div[1]/div/div/div/div/ul/li[8]")
driver.execute_script("arguments[0].click();", element6)
element9 = driver.find_element_by_xpath("//*[@id='delete-tweet-dialog-dialog']/div[2]/div[4]/button[2]")
driver.execute_script("arguments[0].click();", element9)



















